#!/bin/sh

ETH0_MAC_FILE="/etc/.eth0_macaddr"
USB0_MAC_FILE="/etc/.usb0_macaddr"

start() {
	if ifconfig -a | grep -q 'usb0'; then
		ifconfig usb0 up

		USB0_CURRENT_MAC=$(cat /sys/class/net/usb0/address)

		if [ -f "$USB0_MAC_FILE" ]; then
			USB0_SAVED_MAC=$(cat "$USB0_MAC_FILE")
			if [ -z "$USB0_SAVED_MAC" ];then
				rm $USB0_MAC_FILE
				echo "$USB0_CURRENT_MAC" > "$USB0_MAC_FILE"
				echo "[S60netdevice] Saved current MAC address ($USB0_CURRENT_MAC) to $USB0_MAC_FILE"
			else
				echo "[S60netdevice] Saved usb0 Mac address:$USB0_SAVED_MAC"
				ifconfig usb0 down
				ifconfig usb0 hw ether "$USB0_SAVED_MAC"
				ifconfig usb0 up
				echo "[S60netdevice] Set usb0 MAC address to $USB0_SAVED_MAC"
			fi
		else
			echo "$USB0_CURRENT_MAC" > "$USB0_MAC_FILE"
			echo "[S60netdevice] Saved current MAC address ($USB0_CURRENT_MAC) to $USB0_MAC_FILE"
		fi

		ifconfig usb0 192.168.123.100
	else
		echo "[S60netdevice] usb0 not found"
	fi
}

case "$1" in
	start)
		start &
		;;
	*)
		exit 1
		;;
esac
