#!/bin/sh

ETH0_MAC_FILE="/etc/.eth0_macaddr"
USB0_MAC_FILE="/etc/.usb0_macaddr"

start() {
	nohup /usr/bin/usb-net-up.sh 2>&1 >/dev/null &
}

case "$1" in
	start)
		start &
		;;
	*)
		exit 1
		;;
esac
